{% set name = "BiGER" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --force-reinstall --no-deps -vv "

requirements:
  build:
    - python
    - setuptools
  host:
    - python
  run:
    - python >=3.9

test:
  requires:
    - pytest
    - pytest-cov
    - coverage
    - pytest-mock
  imports:
    - BiGER
    - numpy >= 1.21
    - scipy
    

about:
  home: https://github.com/kevin931/BiGER-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python implementation of BiGER for Bayesian Aggregation in Genomics with Extended Ranking Schemes.

extra:
  recipe-maintainers:
    - kevin931